#!/bin/bash

set -e

DOCK_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Source modules
source "$DOCK_DIR/lib/constants.sh"
source "$DOCK_DIR/lib/utils.sh"
source "$DOCK_DIR/lib/commands/config.sh"
source "$DOCK_DIR/lib/commands/docker.sh"
source "$DOCK_DIR/lib/commands/app.sh"
source "$DOCK_DIR/lib/commands/node.sh"
source "$DOCK_DIR/lib/commands/db.sh"

# Main command router
case "$1" in
    use)        cmd_use "$2" ;;
    which)      cmd_which ;;
    init)       cmd_init ;;
    config)     cmd_config ;;
    start)      cmd_start ;;
    stop)       cmd_stop ;;
    restart)    cmd_restart ;;
    destroy)    cmd_destroy ;;
    status)     cmd_status ;;
    logs)       cmd_logs "$2" ;;
    shell)      cmd_shell ;;
    root)       cmd_root ;;
    mysql)      cmd_mysql ;;
    artisan)    shift; cmd_artisan "$@" ;;
    composer)   shift; cmd_composer "$@" ;;
    npm)        shift; cmd_npm "$@" ;;
    npx)        shift; cmd_npx "$@" ;;
    yarn)       shift; cmd_yarn "$@" ;;
    dev)        cmd_dev ;;
    build-assets) cmd_build_assets ;;
    build)      cmd_build ;;
    install)    cmd_install ;;
    help|"")    show_help ;;
    *)          print_error "$MSG_ERR_UNKNOWN_CMD $1"; show_help; exit 1 ;;
esac
